config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  resources :payments
  concern :searchable do
    collection do
      get 'search'
    end
  end
  namespace :admin do
    resources :bank_accounts
    resources :companies
    resources :equipment
    resources :equipment_brands
    resources :equipment_models,concerns: [:searchable]
    resources :equipment_types
    resources :establishment_services
    resources :establishments
    resources :invoices_patients,concerns: [:searchable]
    resources :plans
    resources :positions
    resources :permissions
    resources :roles
    resources :skills
    resources :user_skills, only: [:show,:destroy]
    resources :specialities
    resources :forms
    resources :insurance_files, only: [:show,:destroy]
    resources :patients
    resources :patient_draft_data do
      collection do
        post 'save_upload_file', to: 'patient_draft_data/save_upload_file'
      end
    end
    resources :settings do
      collection do
        put 'update_settings',to: 'settings/update_settings'
      end
    end
    resources :users,concerns: [:searchable] do
      collection do
        get "pre_creation_user", to: 'users#pre_creation_user', :as => "pre_creation_user"
        get "accounts_to_active", to: 'users#accounts_to_active', :as => "accounts_to_active"
        get "pending_accounts", to: 'users#pending_accounts', :as => "pending_accounts"
        get "active_accounts", to: 'users#active_accounts', :as => "active_accounts"
        get "deactive_accounts", to: 'users#deactive_accounts', :as => "deactive_accounts"
        get "get_del_cust_by_country", to: 'users#get_del_cust_by_country', :as => "get_del_cust_by_country"
        get "set_current_role", to: 'users#set_current_role', :as => "set_current_role"
      end
      member do
        get "show_signature", to: 'users#show_signature', :as => "show_signature"
        put "delete_signature", to: 'users#delete_signature', :as => "delete_signature"
        get "active_account_form", to: 'users#active_account_form', :as => "active_account_form"
        post "update_account_status", to: 'users#update_account_status'
      end
    end
    # resources :users
    post "users/checkpostalcode", to: 'users#checkpostalcode', :as => "checkpostalcode"
    get "users/approved_data",to: 'users#approved_data', :as =>"approved_data"
    # get "users/pre_creation_user", to: 'users#pre_creation_user', :as => "pre_creation_user"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    password_expired: 'users/password_expired'

  }
  devise_scope :user do
    get 'signup' => 'users/registrations#new', :as => :sign_up
    # post 'signup' => 'users/registrations#new', :as => :sign_up
    authenticated :user do
      root 'dashboard#show'
    end
    get 'users/password_expired/change_password'
    post 'users/password_expired/update_password'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "devise/sessions#new"
  # root 'home#index'
  # resources "users"
  post '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  post '/set_role', to: 'settings#set_role_before_sign_up', as: :set_role_before_sign_up
  get '/get_users', to: 'settings#get_users'
  get '/find_customer_id', to: 'settings#find_customer_id'
  get '/find_patient_id', to: 'settings#find_patient_id'
  get '/find_provider_id', to: 'settings#find_provider_id'
  get '/find_delegate_customer_id', to: 'settings#find_delegate_customer_id'
  get '/find_salesman_before_sale_id', to: 'settings#find_salesman_before_sale_id'
  get '/find_salesman_sav_id', to: 'settings#find_salesman_sav_id'
  get '/find_physician_id', to: 'settings#find_physician_id'
  get '/get_all_skills', to: 'settings#get_all_skills'
  get '/mark_notification_as_read', to: 'settings#mark_notification_as_read'
  resources :forms do
    member do 
      get ':form_name' => "forms#payment_of_analysis", as: :payment_of_analysis
    end
  end

  resources :establishments, only: [:index]
  resources :establishment_services, only: [:index]
  resources :role_selection,only: [:index]
  post 'role_selection/get_role_id'
  get '/admin/establishment_form_check_postal_code', to: 'settings#establishment_form_check_postal_code'
  get '/admin/new_user_form_check_postal_code', to: 'settings#new_user_form_check_postal_code'
  get '/admin/change_notification_value', to: 'settings#change_notification_value'
end

app/views/layouts/shared/_administrator_sidebar.html.erb
<aside class="sidepanel open">
  <ul class="nav nav-stacked primary-nav">
    <li class="dropdown" id="dashboard">
      <a href="<%= root_path %>" class="root-user-menu"><span><%= t('activerecord.menus.admin.dashboard') %></span></a>
    </li>
    <li class="dropdown">
      <a href="javascript:;" class="root-user-menu" id="master-table-menu-link"><span><%= t('activerecord.menus.admin.account.account') %></span><i class="fa fa-chevron-down pull-right"></i></a>
      <ul class="nav nav-stacked collapsible-menu" id="0">
        <li class=""><%= link_to pending_accounts_admin_users_path do %><span><%= t('activerecord.menus.admin.account.pending') %></span><% end %></li>
        <li class=""><%= link_to active_accounts_admin_users_path do %><span><%= t('activerecord.menus.admin.account.active') %></span><% end %></li>
        <li class=""><%= link_to deactive_accounts_admin_users_path do %><span><%= t('activerecord.menus.admin.account.inactive') %></span><% end %></li>
        <li class=""><%= link_to new_admin_user_path do %><span><%= t('activerecord.menus.admin.account.new_account') %></span><% end %></li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="root-user-menu"><span><%= t('activerecord.menus.admin.database.database') %></span><i class="fa fa-chevron-down pull-right"></i></a>
      <ul class="nav nav-stacked collapsible-menu" id="1">
        <li class="<%= check_current_ctrl('equipment') %>"><%= link_to admin_equipment_index_path do %><span><%= t('activerecord.menus.admin.database.equipment') %></span><% end %></li>
        <li class="<%= check_current_ctrl('skills') %>"><%= link_to admin_skills_path do %><span><%= t('activerecord.menus.admin.database.skills') %></span><% end %></li>
        <li class="<%= check_current_ctrl('specialities') %>"><%= link_to admin_specialities_path do %><span><%= t('activerecord.menus.admin.database.specialities') %></span><% end %></li>
        <li class="<%= check_current_ctrl('permissions') %>"><%= link_to admin_permissions_path do %><span><%= t('activerecord.menus.admin.database.permissions') %></span><% end %></li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="root-user-menu"><span><%= t('activerecord.menus.admin.administrative.administrative') %></span><i class="fa fa-chevron-down pull-right"></i></a>
      <ul class="nav nav-stacked collapsible-menu " id="2">
        <li class=""><%= link_to "#" do %><span><%= t('activerecord.menus.admin.administrative.invoices') %></span><% end %></li>
        <li class="<%= check_current_ctrl('plans') %>"><%= link_to admin_plans_path do %><span><%= t('activerecord.menus.admin.administrative.plans') %></span><% end %></li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="root-user-menu"><span><%= t('activerecord.menus.admin.activity.activity') %></span><i class="fa fa-chevron-down pull-right"></i></a>
      <ul class="nav nav-stacked collapsible-menu ">
        <li class=""><%= link_to "#" do %><span><%= t('activerecord.menus.admin.activity.pending_files') %></span><% end %></li>
        <li class=""><%= link_to "#" do %><span><%= t('activerecord.menus.admin.activity.statistics') %></span><% end %></li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="root-user-menu" id="master-table-menu-link"><span><%= t('activerecord.menus.admin.master.master') %></span>  <i class="fa fa-chevron-down pull-right"></i></a>
      <ul class="nav nav-stacked collapsible-menu " id="3">
        <li class="<%= check_current_ctrl('bank_accounts') %>"><%= link_to admin_bank_accounts_path do %><span><%= t('activerecord.menus.admin.master.bank_accounts') %></span><% end %></li>
        <li class="<%= check_current_ctrl('equipment') %>"><%= link_to admin_equipment_index_path do %><span><%= t('activerecord.menus.admin.master.equipment') %></span><% end %></li>
        <li class="<%= check_current_ctrl('equipment_brands') %>"><%= link_to admin_equipment_brands_path do %><span><%= t('activerecord.menus.admin.master.equipment_brands') %></span><% end %></li>
        <li class="<%= check_current_ctrl('equipment_models') %>"><%= link_to admin_equipment_models_path do %><span><%= t('activerecord.menus.admin.master.equipment_models') %></span><% end %></li>
        <li class="<%= check_current_ctrl('equipment_types') %>"><%= link_to admin_equipment_types_path do %><span><%= t('activerecord.menus.admin.master.equipment_types') %></span><% end %></li>
        <li class="<%= check_current_ctrl('establishment_services') %>"><%= link_to admin_establishment_services_path do %><span><%= t('activerecord.menus.admin.master.establishment_services') %></span><% end %></li>
        <li class="<%= check_current_ctrl('establishments') %>"><%= link_to admin_establishments_path do %><span><%= t('activerecord.menus.admin.master.establishments') %></span><% end %></li>
        <li><a href="#"><span><%= t('activerecord.menus.admin.master.invoices') %></span></a></li>
        <li class="<%= check_current_ctrl('invoices_patient') %>"><%= link_to admin_invoices_patients_path do %><span><%= t('activerecord.menus.admin.master.patient_invoice') %></span><% end %></li>
        <li class="<%= check_current_ctrl('plans') %>"><%= link_to admin_plans_path do %><span><%= t('activerecord.menus.admin.master.plans') %></span><% end %></li>
        <li class="<%= check_current_ctrl('positions') %>"><%= link_to admin_positions_path do %><span><%= t('activerecord.menus.admin.master.positions') %></span><% end %></li>
        <!-- <li class="<%#= check_current_ctrl('roles') %>"><%#= link_to admin_roles_path do %><span>Roles</span><%# end %></li> -->
        <li class="<%= check_current_ctrl('skills') %>"><%= link_to admin_skills_path do %><span><%= t('activerecord.menus.admin.master.skills') %></span><% end %></li>
        <li class="<%= check_current_ctrl('specialities') %>"><%= link_to admin_specialities_path do %><span><%= t('activerecord.menus.admin.master.specialities') %></span><% end %></li>
        <li><a href="#"><span><%= t('activerecord.menus.admin.master.subscription') %></span></a></li>
        <li class="<%= check_current_ctrl('settings') %>"><%= link_to admin_settings_path do %><span><%= t('activerecord.menus.admin.master.settings') %></span><% end %></li>
        <li class="<%= check_current_ctrl('forms') %>"><%= link_to admin_forms_path do %><span><%= t('activerecord.menus.admin.master.upload_file') %></span><% end %></li>
        <li class="check_current_ctrl('users')"><%= link_to admin_users_path do %><span><%= t('activerecord.menus.admin.master.user') %></span><% end %></li>
        <% if has_permission('admin/users',"accounts_to_active") %>
          <li class="check_current_ctrl('users')"><%= link_to accounts_to_active_admin_users_path do %><span><%= t('activerecord.menus.admin.master.list_of_accounts_to_activate') %></span><% end %></li>
        <% end %>
      </ul>
    </li>
  </ul>
</aside>

app/views/layouts/shared/_after_signup_header.html.erb
<header class="header">
  <nav class="navbar dark-gray-bg navbar-fixed-top">
    <div class="vertical-middle">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
        <div class="row">
          <div class="col-md-3">
              <div class="navbar-header">
                  <a class="navbar-brand" href="#">
                      <h2 class="white-text">ZANALYS</h2>
                  </a>
              </div>
              <button type="button" class="navbar-toggle" data-toggle="collapse" aria-expanded="false">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
          </div>
          <div class="col-md-9">
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right localize-lang-droplist">
                <!-- Localize droplist -->
                <li class="dropdown locale-dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <% if I18n.locale == :en %>
                      <span data-value="en"><%= "English" %></span>
                    <% elsif I18n.locale == :fr %>
                      <span data-value="fr"><%= "French" %></span>
                    <% end %>
                    <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li>
                        <%= button_to "English", change_locale_path(:en), class: "btn btn-link a-to-btn" %>
                      </li>
                      <li>
                        <%= button_to "French", change_locale_path(:fr), class: "btn btn-link a-to-btn" %>
                      </li>
                  </ul>
                </li>
                <!-- <li class="dropdown role-dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span data-value="en"><%#= Role %></span>
                    <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>
                      <%#= select_tag :user_role, options_for_select(current_user.roles.collect { |r| [r.name_en, r.id]}),{class: "form-control selectpicker",data: {live_search: true} }%>
                    </li>
                  </ul>
                </li> -->
                <!-- <li>
                    <form action="#" method="#">
                        <div class="search">
                            <input type="text" class="form-control header_search" id="search" placeholder="<%#= I18n.t('search') %>">
                        </div>
                    </form>
                </li> -->
                <li class="dropdown">
                    <div class="profile vertical  dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <div class="vertical-middle">
                            <a href="#">
                                <%= image_tag current_user.photo.url,class: "img-circle img-responsive",alt: "" %>
                                <span><%= current_user.full_name || current_user.email %></span>
                            </a>
                        </div>
                    </div>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Profile",edit_user_registration_path %></li>
                        <li>
                          <%= select_tag :user_role, options_for_select(current_user.roles.collect { |r| [r.name_en, r.id]},[current_role.id]),{class: "form-control",prompt: "select role" }%>
                        </li>
                        <li><%= link_to 'Log out', destroy_user_session_path, method: :get %></li>
                    </ul>
                </li>
                <%= render 'layouts/shared/user_notifications' %>
                <!-- <%# if @notifications.present? %>
                  <li class="dropdown">
                      <div class="profile vertical  dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                          <div class="vertical-middle">
                              <a href="#">
                                  <i class="fa fa-bell-o"></i>
                                    <%# if @notifications.present? %>
                                      <span class="label label-warning notification">New</span>
                                    <%# else %>
                                      <span class="label notification"></span>
                                    <%# end %>
                              </a>
                          </div>
                      </div>
                      <ul class="dropdown-menu">
                        <%# if @notifications.present? %>
                            <%# @notifications.each do |notification| %>
                              <li><a href='<%#= notification.url %>' onclick="setNotificationToFalse(this)"><%#= notification.message %></a></li>
                            <%# end %>
                        <%# else %>
                        <li>No notifications</li>
                        <%# end %>
                      </ul>
                  </li>
                <%# end %> -->
              </ul>
            </div>
          </div>
        </div>
          <!-- /.navbar-collapse -->
      </div>
    </div>
      <!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/shared/_notification.html.erb
<li class = "<%= notification.is_read ? 'read_class' : 'unread_class'  %>">
  <a id="notification-redirect-link" href="<%= notification.redirect_url %>" data-notification-id="<%= notification.id %>" data-turbolinks="off">
    <h4><%= notification.title %></h4>
    <p><%= notification.description %></p>
  </a>
</li>
<li class="divider"></li>

app/views/layouts/shared/_sidebar.html.erb
<aside class="sidepanel open">
  <ul class="nav nav-stacked primary-nav">
    <li class="dropdown">
      <a href="<%= root_path %>" class="master-link"><span><%= t('activerecord.menus.admin.dashboard') %></span></a>
    </li>
    <li class="dropdown">
      <a href="#" class="master-link" id="master-table-menu-link"><span><%= t('activerecord.menus.admin.master.master') %></span>  <i class="fa fa-chevron-down pull-right"></i></a>
      <ul class="nav nav-stacked collapsible-menu ">
        <li class="<%= check_current_ctrl('bank_accounts') %>"><%= link_to admin_bank_accounts_path do %><span><%= t('activerecord.menus.admin.master.bank_accounts') %></span><% end %></li>
        <li class="<%= check_current_ctrl('equipment') %>"><%= link_to admin_equipment_index_path do %><span><%= t('activerecord.menus.admin.master.equipment') %></span><% end %></li>
        <li class="<%= check_current_ctrl('equipment_brands') %>"><%= link_to admin_equipment_brands_path do %><span><%= t('activerecord.menus.admin.master.equipment_brands') %></span><% end %></li>
        <li class="<%= check_current_ctrl('equipment_models') %>"><%= link_to admin_equipment_models_path do %><span><%= t('activerecord.menus.admin.master.equipment_models') %></span><% end %></li>
        <li class="<%= check_current_ctrl('equipment_types') %>"><%= link_to admin_equipment_types_path do %><span><%= t('activerecord.menus.admin.master.equipment_types') %></span><% end %></li>
        <li class="<%= check_current_ctrl('establishment_services') %>"><%= link_to admin_establishment_services_path do %><span><%= t('activerecord.menus.admin.master.establishment_services') %></span><% end %></li>
        <li class="<%= check_current_ctrl('establishments') %>"><%= link_to admin_establishments_path do %><span><%= t('activerecord.menus.admin.master.establishments') %></span><% end %></li>
        <li><a href="#"><span><%= t('activerecord.menus.admin.master.invoices') %></span></a></li>
        <li class="<%= check_current_ctrl('plans') %>"><%= link_to admin_plans_path do %><span><%= t('activerecord.menus.admin.master.plans') %></span><% end %></li>
        <li class="<%= check_current_ctrl('positions') %>"><%= link_to admin_positions_path do %><span><%= t('activerecord.menus.admin.master.positions') %></span><% end %></li>
        <!-- <li class="<%#= check_current_ctrl('roles') %>"><%#= link_to admin_roles_path do %><span>Roles</span><%# end %></li> -->
        <li class="<%= check_current_ctrl('skills') %>"><%= link_to admin_skills_path do %><span><%= t('activerecord.menus.admin.master.skills') %></span><% end %></li>
        <li class="check_current_ctrl('specialities')"><%= link_to admin_specialities_path do %><span><%= t('activerecord.menus.admin.master.specialities') %></span><% end %></li>
        <li><a href="#"><span><%= t('activerecord.menus.admin.master.subscription') %></span></a></li>
        <li class="<%= check_current_ctrl('forms') %>"><%= link_to admin_forms_path do %><span><%= t('activerecord.menus.admin.master.upload_file') %></span><% end %></li>
        <li class="check_current_ctrl('users')"><%= link_to admin_users_path do %><span><%= t('activerecord.menus.admin.master.user') %></span><% end %></li>
        <% if has_permission('admin/users',"accounts_to_active") %>
          <li class="check_current_ctrl('users')"><%= link_to accounts_to_active_admin_users_path do %><span><%= t('activerecord.menus.admin.master.list_of_accounts_to_activate') %></span><% end %></li>
        <% end %>
      </ul>
    </li>
    <li class="dropdown">
      <a href="<%= admin_permissions_path %>" class="master-link"><span>Manage Permissions</span></a>
    </li>
  </ul>
</aside>

app/views/layouts/shared/_signup_header.html.erb
<header class="header">
  <nav class="navbar dark-gray-bg navbar-fixed-top">
    <div class="vertical-middle">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="#">
            <h2 class="white-text">ZANALYS</h2>
          </a>
        </div>
        <!-- Localize droplist -->
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown" class="white-text">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <% if I18n.locale == :en %>
                <span data-value="en"><%= "English" %></span>
              <% elsif I18n.locale == :fr %>
                <span data-value="fr"><%= "French" %></span>
              <% end %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "English", change_locale_path(:en), class: "sub-menu", data: { value: "en" } %></li>
              <li><%= link_to "French", change_locale_path(:fr), class: "sub-menu", data: { value: "fr" } %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/shared/_user_notifications.html.erb
<li class="dropdown notification">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button " aria-haspopup="true " aria-expanded="false ">
      <i class="fa fa-bell-o"></i>
      <span class="badge"><%= unread_notification_count %></span>
  </a>
  <ul class="dropdown-menu" id="notification-list">
    <%= render partial: 'layouts/shared/notification', collection: get_current_user_notifications %>
  </ul>
</li>