config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  resources :payments
  concern :searchable do
    collection do
      get 'search'
    end
  end
  namespace :admin do
    resources :bank_accounts
    resources :companies
    resources :equipment
    resources :equipment_brands
    resources :equipment_models,concerns: [:searchable]
    resources :equipment_types
    resources :establishment_services
    resources :establishments
    resources :invoices_patients,concerns: [:searchable]
    resources :plans
    resources :positions
    resources :permissions
    resources :roles
    resources :skills
    resources :user_skills, only: [:show,:destroy]
    resources :specialities
    resources :forms
    resources :insurance_files, only: [:show,:destroy]
    resources :patients
    resources :patient_draft_data do
      collection do
        post 'save_upload_file', to: 'patient_draft_data/save_upload_file'
      end
    end
    resources :settings do
      collection do
        put 'update_settings',to: 'settings/update_settings'
      end
    end
    resources :users,concerns: [:searchable] do
      collection do
        get "pre_creation_user", to: 'users#pre_creation_user', :as => "pre_creation_user"
        get "accounts_to_active", to: 'users#accounts_to_active', :as => "accounts_to_active"
        get "pending_accounts", to: 'users#pending_accounts', :as => "pending_accounts"
        get "active_accounts", to: 'users#active_accounts', :as => "active_accounts"
        get "deactive_accounts", to: 'users#deactive_accounts', :as => "deactive_accounts"
        get "get_del_cust_by_country", to: 'users#get_del_cust_by_country', :as => "get_del_cust_by_country"
        get "set_current_role", to: 'users#set_current_role', :as => "set_current_role"
      end
      member do
        get "show_signature", to: 'users#show_signature', :as => "show_signature"
        put "delete_signature", to: 'users#delete_signature', :as => "delete_signature"
        get "active_account_form", to: 'users#active_account_form', :as => "active_account_form"
        post "update_account_status", to: 'users#update_account_status'
      end
    end
    # resources :users
    post "users/checkpostalcode", to: 'users#checkpostalcode', :as => "checkpostalcode"
    get "users/approved_data",to: 'users#approved_data', :as =>"approved_data"
    # get "users/pre_creation_user", to: 'users#pre_creation_user', :as => "pre_creation_user"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    password_expired: 'users/password_expired'

  }
  devise_scope :user do
    get 'signup' => 'users/registrations#new', :as => :sign_up
    # post 'signup' => 'users/registrations#new', :as => :sign_up
    authenticated :user do
      root 'dashboard#show'
    end
    get 'users/password_expired/change_password'
    post 'users/password_expired/update_password'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "devise/sessions#new"
  # root 'home#index'
  # resources "users"
  post '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  post '/set_role', to: 'settings#set_role_before_sign_up', as: :set_role_before_sign_up
  get '/get_users', to: 'settings#get_users'
  get '/find_customer_id', to: 'settings#find_customer_id'
  get '/find_patient_id', to: 'settings#find_patient_id'
  get '/find_provider_id', to: 'settings#find_provider_id'
  get '/find_delegate_customer_id', to: 'settings#find_delegate_customer_id'
  get '/find_salesman_before_sale_id', to: 'settings#find_salesman_before_sale_id'
  get '/find_salesman_sav_id', to: 'settings#find_salesman_sav_id'
  get '/find_physician_id', to: 'settings#find_physician_id'
  get '/get_all_skills', to: 'settings#get_all_skills'
  get '/mark_notification_as_read', to: 'settings#mark_notification_as_read'
  resources :forms do
    member do 
      get ':form_name' => "forms#payment_of_analysis", as: :payment_of_analysis
    end
  end

  resources :establishments, only: [:index]
  resources :establishment_services, only: [:index]
  resources :role_selection,only: [:index]
  post 'role_selection/get_role_id'
  get '/admin/establishment_form_check_postal_code', to: 'settings#establishment_form_check_postal_code'
  get '/admin/new_user_form_check_postal_code', to: 'settings#new_user_form_check_postal_code'
  get '/admin/change_notification_value', to: 'settings#change_notification_value'
end

app/models/permission.rb
class Permission < ApplicationRecord
	has_many :role_permissions
	has_many :roles, through: :role_permissions, dependent: :destroy
	validates :name_en, presence: true
	accepts_nested_attributes_for :role_permissions, allow_destroy: true

	scope :include_permission, -> { where "subject_class NOT IN (?)",EXPECT_CONTROLLER }

	def find_role(custom_role_id)
		return self.role_permissions.find_by(role_id: custom_role_id).present?
	end

	def name_with_local
		I18n.locale == 'en' ? name_en : name_fr
	end
end

app/models/role.rb
class Role < ApplicationRecord
	validates :name_en,:name_fr, presence: true,uniqueness: true
  # validates :permissions, presence: true
	has_many :role_permissions
	has_many :permissions, through: :role_permissions, dependent: :destroy
	has_many :user_roles
  has_many :users, through: :user_roles,dependent: :destroy

	enum custom_role_id: { :root => 0, :IT_admin => 1, :manager => 2, :internal_physician_supervisor => 3,:customer => 4,:delegated_customer => 5,:establishment_admin => 6,:service_admin => 7,:physician => 8,:technical_service_provider => 9,:admin_staff => 10,:salesman_before_sale => 11,:salesman => 12,:patient => 13 }

	scope :protected_roles, -> { where(protected: 1) }
	SALESMAN_ROLE = ["salesman_before_sale"]
	scope :salesman_roles, -> { where("custom_role_id = ?",SALESMAN_ROLE) }
	
  def name_with_local
    I18n.locale == 'en' ? name_en : name_fr
  end

  def self.role_access
  	roles = ["Root" ,"IT Administrator", "Manager", "Internal Physician Supervisor"]
  	@check_roles = self.where("name_en not IN (?)",roles)
  	return @check_roles
  end
end

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController <  Admin::BaseController
	include ApplicationHelper
	before_action :check_permission,only: [:index,:edit,:update]
	before_action :check_role, only: [:update]
  after_action :set_redirect_path, only: [:new, :edit]

	def resource_class
		Role
	end

	# def configure_redirect_path
	# 	redirect_to admin_permissions_path
	# end

	def resource_name
		"role"
	end

	private

	def permitted_attributes
		["name_en", "name_fr", "protected", "custom_role_id", permission_ids: []]
	end

	def check_role
		if @resource.protected == 1 &&  params[:role][:name_fr]
			unless @resource.name_fr == params[:name_fr]
				redirect_to root_path, :alert => "You can't change role name in french"
			end
		end
	end

	def check_permission
		unless has_permission("admin/roles","create") || has_permission("admin/roles","update")
		# unless current_user.has_role?("root")
			flash[:alert] = "Access denied. You are not authorized to access the requested page."
      redirect_to root_path
		end
	end

	def set_redirect_path
    session[:redirect_back] = { controller: controller_name, action: "index" }
  end
end

app/helpers/admin/permissions_helper.rb
module Admin::PermissionsHelper
end

app/views/admin/permissions/_actions.html.erb
<%= link_to "New Role with Permissions", new_admin_permission_path ,class: "btn btn-default gray-bg",style: "margin-top: 10px;"%>
<%#= link_to "New Role", new_admin_role_path ,class: "btn btn-default gray-bg",style: "margin-top: 10px;"%>

app/views/admin/permissions/_dynamic_permission.html.erb
<!-- <table border="0" cellspacing="0" cellpadding="0" id="index_table_permissions" class="index_table index">
	<%#=semantic_form_for [:admin,@permission] do |f| %>
		<%#count = role.count %>
		<thead>
			<tr>
				<th rowspan="3">
					Module
				</th>
				<th colspan="<%#= count %>" style="text-align: center;">
					Role/Permission
				</th>
				<tr>
					<%# role.each do |role| %>
						<th><%# if I18n.locale == :en %>
									<%#=role.name_en.capitalize%>
								<%# elsif I18n.locale == :fr %>
									<%#=role.name_fr.capitalize%>
								<%# end %><br>C|E|R|D</th>
					<%#end %>
				</tr>
			</tr>
		</thead>

		<tbody>
				<tr>
					<td>
						<%#include_controller.each do |controller| %>
							<div style="float: left;width: 100%;height: 30px;"><%#=controller %></div>
						<%#end %>
							<br>
					</td>
					<%#role.find_each do |r| %>
						<td>
							<div style="float: left;width: 100%;height: 30px;">
								<%#cnt=0 %>
								<%#all_controller.includes(:role_permissions).find_each do |p| %>
									<%#= f.input :permissions, :as => :check_boxes,:collection=>all_controller.ids.inject({}) { |p,r| p[r] = role.ids[all_controller.ids]},:label=>false %>
									<%#= f.check_box :permissions,all_controller.map{ |p| ["",r.id.to_s + "/" + p.id.to_s]}%>
									<%#cnt=cnt +1 %>
							    <%#=check_box_tag "permission[permissions][]", r.id.to_s + "/" + p.id.to_s,p.find_role(r.custom_role_id)%>
							    <%#if cnt >= 4 %>
							    	<br>
							    <%#end %>
							    <%#if cnt == 4 %>
							    	<%#cnt=0 %></div><div style="float: left;width: 100%;height: 30px;">
							    <%#end %>
							  <%#end %>
						  </div>
						</td>
					<%#end %>
				</tr>
			<tr>
				<td colspan="<%#= count + 1 %>" style="text-align: center;"><%#= f.button :save ,:class=>"btn-save"%></button></td>
			</tr>
		</tbody>
	<%#end %>
</table> -->
<%= form_for [:admin, @resource],class: "form-horizontal" do |f| %>
<% @resources.each do |resource|  %>
 	<%= collection_check_boxes :role, :permission_ids, Permission.all, :id, :name_with_local, :include_hidden => false do |permission| %>
	<%= permission.label do %>
		<%= permission.text %>
		<%= permission.check_box checked:  %>
	<% end %>
<% end %>
<% end %>
<% end %>

app/views/admin/permissions/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <h2><%= action_type(@resource) %> Role with permissions</h2>
    </div>
  </div>
  <div class="row">
  	<div class="has-error">
  	  <% if @resource.errors.any? %>
  	    <div class="blockquote-box clearfix">
  	      <span class="help-block">
  	       <b>ERROR:</b>
  	        <ul>
  		        <% @resource.errors.full_messages.each do |msg| %>
  		          <li><%= msg %></li>
  		      	<% end %>
  	     		</ul>
  	     </span>
  	    </div>
  	  <% end %>
  	</div>
  </div>
  <div class="row">
    <div class="col-md-12">
    	<%= form_for [:admin, @resource], class: "form-horizontal" do |f| %>
       <%= hidden_field_tag "role[permission_ids][]", nil %>
        <div id="search-information" class="box white-bg">
          <div class="form-group">
            <div class="row">
              <div class="col-md-6 col-sm-6">
                <label for="name_en" class="col-sm-12">name_en</label>
               	<%= f.text_field :name_en,class: "form-control",placeholder: "name_en",required: "required" %>
              </div>
              <div class="col-md-6 col-sm-6">
                <label for="name_fr" class="col-sm-12">name_fr</label>
                <% if @resource.protected == 1 %>
               	  <%= f.text_field :name_fr,class: "form-control",placeholder: "name_fr",required: "required",disabled: true %>
                <% else %>
                  <%= f.text_field :name_fr,class: "form-control",placeholder: "name_fr",required: "required" %>
                <% end %>
              </div>
              <div class="col-md-6 col-sm-6">
                <h1>Permissions</h1>
                <% roles = Role.includes(:permissions).all %>
                
                <% uniq_controller = Permission.all.group_by { |p| p.title } %>

                <div class="accordion panel-group" id="accordion2">
                  <% uniq_controller.each do |permission| %>
                
                      <div class="panel panel-default">
                        <%= link_to "##{permission.first}" ,data: {parent: "#accordion2", toggle: "collapse"} do %>
                          <div class="panel-heading">
                              <h3 class="panel-title">
                                 <%= permission&.first&.gsub("_"," ") %>
                              </h3>
                          </div>
                        <% end %>
                        <div id="<%= permission.first %>" class="panel-collapse collapse">
                          <div class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                            <div class="card-block">
                              <table>
                                <% permission.second.each do |cont| %>
                                
                                  
                                    <tr>
                                      <td><%= I18n.locale == :en ? cont.name_en : cont.name_fr%></td>
                                      <td>
                                        <%= f.check_box :permission_ids, {multiple: true}, cont.id, nil %></td>
                                    </tr>
                                  
                                <% end %>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                  <% end %>
                </div>
              </div>
              <div class="col-md-2 col-md-offset-10 col-sm-4">
              	<%= f.submit action_type_for_button(@resource),class: "btn btn-default gray-bg pull-right" %> 
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/permissions/_permission.html.erb
<tr>
	<td><%= role.name_en %></td>
	<td><%= role.name_fr %></td>
	<td>
			<%# if has_permission(controller_path,"update") %>
		<%= link_to edit_admin_permission_path(role) do %><i class="fa fa-edit"></i><% end %>
		<% if can? :manage, role %>
			<%# end %>
			<%# if has_permission(controller_path,"destroy") %>
				<%= link_to admin_permission_path(role), data: { confirm: "Are you sure ?" }, method: :delete do %><i class="fa fa-trash"></i><% end %>
			<%# end %>
		<% end %>
		</td>
</tr>

app/views/admin/permissions/edit.html.erb
<%= render "form" %>

app/views/admin/permissions/index.html.erb
<%#= render 'dynamic_permission' %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9 col-sm-9">
      <h2>Role with permissions</h2>
    </div>
    <div class="col-md-3 col-sm-3">
    	<%= render "actions" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% if has_permission(controller_path,"search") %>
        <form method="#" action="#" class="form-horizontal">
          <div id="search-information" class="box white-bg">
            <div class="form-heading">
                <h3>search</h3>
                <div class="divider dark-gray-bg"></div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-md-4 col-sm-4">
                  <label for="provider" class="col-sm-12">Provider</label>
                  <select name="provider" class="form-control ">
                    <option value=" ">Select a Provider</option>
                    <option value="1 ">1</option>
                    <option value="2 ">2</option>
                  </select>
                </div>
                <div class="col-md-4 col-sm-4">
                  <label for="model" class="col-sm-12">Model</label>
                  <select name="model" class="form-control ">
                    <option value=" ">Select a Model</option>
                    <option value="1 ">1</option>
                    <option value="2 ">2</option>
                  </select>
                </div>
                <div class="col-md-4 col-sm-4">
                  <label for="serial-number" class="col-sm-12">Serial number</label>
                  <select name="serial-number" class="form-control ">
                    <option value=" ">Select a Serial number</option>
                    <option value="1 ">1</option>
                    <option value="2 ">2</option>
                  </select>
                </div>
                <div class="col-md-2 col-md-offset-10 col-sm-2 col-sm-offset-10">
                  <button type="button " class="btn btn-default gray-bg pull-right">
                      Search
                  </button>
                </div>
              </div>
            </div>
          </div>
        </form>
      <% end %>
      <div id="search-information" class="box white-bg">
        <div class="table-responsive">
          <table class="table">
            <thead class="table-heading">
              <tr>
                <th>Name En</th>
                <th>Name Fr</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
            	<%= render partial: 'permission', collection: @resources, as: 'role' %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/permissions/new.html.erb
<%= render "form" %>

app/views/admin/permissions/show.html.erb
<br>
<%= render @resource %>
<%= link_to "All", admin_permissions_path %>