config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  resources :payments
  concern :searchable do
    collection do
      get 'search'
    end
  end
  namespace :admin do
    resources :bank_accounts
    resources :companies
    resources :equipment
    resources :equipment_brands
    resources :equipment_models,concerns: [:searchable]
    resources :equipment_types
    resources :establishment_services
    resources :establishments
    resources :invoices_patients,concerns: [:searchable]
    resources :plans
    resources :positions
    resources :permissions
    resources :roles
    resources :skills
    resources :user_skills, only: [:show,:destroy]
    resources :specialities
    resources :forms
    resources :insurance_files, only: [:show,:destroy]
    resources :patients
    resources :patient_draft_data do
      collection do
        post 'save_upload_file', to: 'patient_draft_data/save_upload_file'
      end
    end
    resources :settings do
      collection do
        put 'update_settings',to: 'settings/update_settings'
      end
    end
    resources :users,concerns: [:searchable] do
      collection do
        get "pre_creation_user", to: 'users#pre_creation_user', :as => "pre_creation_user"
        get "accounts_to_active", to: 'users#accounts_to_active', :as => "accounts_to_active"
        get "pending_accounts", to: 'users#pending_accounts', :as => "pending_accounts"
        get "active_accounts", to: 'users#active_accounts', :as => "active_accounts"
        get "deactive_accounts", to: 'users#deactive_accounts', :as => "deactive_accounts"
        get "get_del_cust_by_country", to: 'users#get_del_cust_by_country', :as => "get_del_cust_by_country"
        get "set_current_role", to: 'users#set_current_role', :as => "set_current_role"
      end
      member do
        get "show_signature", to: 'users#show_signature', :as => "show_signature"
        put "delete_signature", to: 'users#delete_signature', :as => "delete_signature"
        get "active_account_form", to: 'users#active_account_form', :as => "active_account_form"
        post "update_account_status", to: 'users#update_account_status'
      end
    end
    # resources :users
    post "users/checkpostalcode", to: 'users#checkpostalcode', :as => "checkpostalcode"
    get "users/approved_data",to: 'users#approved_data', :as =>"approved_data"
    # get "users/pre_creation_user", to: 'users#pre_creation_user', :as => "pre_creation_user"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    password_expired: 'users/password_expired'

  }
  devise_scope :user do
    get 'signup' => 'users/registrations#new', :as => :sign_up
    # post 'signup' => 'users/registrations#new', :as => :sign_up
    authenticated :user do
      root 'dashboard#show'
    end
    get 'users/password_expired/change_password'
    post 'users/password_expired/update_password'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "devise/sessions#new"
  # root 'home#index'
  # resources "users"
  post '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  post '/set_role', to: 'settings#set_role_before_sign_up', as: :set_role_before_sign_up
  get '/get_users', to: 'settings#get_users'
  get '/find_customer_id', to: 'settings#find_customer_id'
  get '/find_patient_id', to: 'settings#find_patient_id'
  get '/find_provider_id', to: 'settings#find_provider_id'
  get '/find_delegate_customer_id', to: 'settings#find_delegate_customer_id'
  get '/find_salesman_before_sale_id', to: 'settings#find_salesman_before_sale_id'
  get '/find_salesman_sav_id', to: 'settings#find_salesman_sav_id'
  get '/find_physician_id', to: 'settings#find_physician_id'
  get '/get_all_skills', to: 'settings#get_all_skills'
  get '/mark_notification_as_read', to: 'settings#mark_notification_as_read'
  resources :forms do
    member do 
      get ':form_name' => "forms#payment_of_analysis", as: :payment_of_analysis
    end
  end

  resources :establishments, only: [:index]
  resources :establishment_services, only: [:index]
  resources :role_selection,only: [:index]
  post 'role_selection/get_role_id'
  get '/admin/establishment_form_check_postal_code', to: 'settings#establishment_form_check_postal_code'
  get '/admin/new_user_form_check_postal_code', to: 'settings#new_user_form_check_postal_code'
  get '/admin/change_notification_value', to: 'settings#change_notification_value'
end

app/models/role.rb
class Role < ApplicationRecord
	validates :name_en,:name_fr, presence: true,uniqueness: true
  # validates :permissions, presence: true
	has_many :role_permissions
	has_many :permissions, through: :role_permissions, dependent: :destroy
	has_many :user_roles
  has_many :users, through: :user_roles,dependent: :destroy

	enum custom_role_id: { :root => 0, :IT_admin => 1, :manager => 2, :internal_physician_supervisor => 3,:customer => 4,:delegated_customer => 5,:establishment_admin => 6,:service_admin => 7,:physician => 8,:technical_service_provider => 9,:admin_staff => 10,:salesman_before_sale => 11,:salesman => 12,:patient => 13 }

	scope :protected_roles, -> { where(protected: 1) }
	SALESMAN_ROLE = ["salesman_before_sale"]
	scope :salesman_roles, -> { where("custom_role_id = ?",SALESMAN_ROLE) }
	
  def name_with_local
    I18n.locale == 'en' ? name_en : name_fr
  end

  def self.role_access
  	roles = ["Root" ,"IT Administrator", "Manager", "Internal Physician Supervisor"]
  	@check_roles = self.where("name_en not IN (?)",roles)
  	return @check_roles
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::BaseController
	include Authorizations
	before_action :prevent_access, except: [:create, :update]
	
	private

	def configure_redirect_path
		redirect_to admin_permissions_path
	end
	
	def permitted_attributes
		["name_en", "name_fr", "protected", "custom_role_id", permission_ids: []]
	end

	def prevent_access
		raise ActionController::RoutingError.new('Not Found')
	end

end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/views/admin/roles/_actions.html.erb
<%= link_to t('role.new_role'), new_admin_role_path ,class: "btn btn-default gray-bg",style: "margin-top: 10px;"%>

app/views/admin/roles/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <h2><%= action_type(@resource) %> Role</h2>
    </div>
  </div>
  <div class="row">
  	<div class="has-error">
  	  <% if @resource.errors.any? %>
  	    <div class="blockquote-box clearfix">
  	      <span class="help-block">
  	       <b>ERROR:</b>
  	        <ul>
  		        <% @resource.errors.full_messages.each do |msg| %>
  		          <li><%= msg %></li>
  		      	<% end %>
  	     		</ul>
  	     </span>
  	    </div>
  	  <% end %>
  	</div>
  </div>
  <div class="row">
    <div class="col-md-12">
    	<%= form_for [:admin, @resource],class: "form-horizontal" do |f| %>
      <%= hidden_field_tag "role[permission_ids][]", nil %>
        <div id="search-information" class="box white-bg">
          <div class="form-group">
            <div class="row">
              <div class="col-md-6 col-sm-6">
                <label for="name_en" class="col-sm-12"><%= t('activerecord.models.role.fields.Name In English') %></label>
               	<%= f.text_field :name_en,class: "form-control",placeholder: "name_en",required: "required" %>
              </div>
              <div class="col-md-6 col-sm-6">
                <label for="name_fr" class="col-sm-12"><%= t('activerecord.models.role.fields.Name In French') %></label>
               	<%= f.text_field :name_fr,class: "form-control",placeholder: "name_fr",required: "required" %>
              </div>
              <div class="col-md-6 col-sm-6">
                <h1>Permissions</h1>
                <% roles = Role.includes(:permissions).all %>
                <% all_controller = Permission.all %>
                <% uniq_controller = Permission.all.uniq.pluck(:subject_class) %>
                  <div class="accordion panel-group" id="accordion2">
                <% uniq_controller.each do |permission| %>
                      <div class="panel panel-default">
                        <%= link_to "##{permission.split('::').join}" ,data: {parent: "#accordion2", toggle: "collapse"} do %>
                          <div class="panel-heading">
                              <h3 class="panel-title">
                                 <%= permission.demodulize == "Registrations" ? "Other" :
                                 (permission.demodulize == "nil" ? "Administration" : permission.demodulize) %>
                              </h3>
                          </div>
                        <% end %>
                        <div id="<%= permission.split('::').join %>" class="panel-collapse collapse">
                          <div class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                            <div class="card-block">
                              <table>
                                <% all_controller.each do |cont| %>
                                  <% if cont.subject_class == permission %>
                                    <tr>
                                      <td><%= I18n.locale == :en ? cont.name_en : cont.name_fr%></td>
                                      <td>
                                        <%= f.check_box :permission_ids, {multiple: true}, cont.id, nil %></td>
                                    </tr>
                                  <% end %>
                                <% end %>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                <% end %>
                  </div>
              </div>
              <div class="col-md-2 col-md-offset-10 col-sm-4">
              	<%= f.submit action_type_for_button(@resource),class: "btn btn-default gray-bg pull-right" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/roles/_role.html.erb
<tr>
	<td><%= role.name_en %></td>
	<td><%= role.name_fr %></td>
	<% if has_permission(controller_path,"update") || has_permission(controller_path,"destroy") %>
		<td>
			<% if can? :manage, role %>
	      	<% if has_permission(controller_path,"update") %>
						<%= link_to edit_admin_role_path(role) do %><i class="fa fa-edit"></i><% end %>
					<% end %>
	      	<% if has_permission(controller_path,"destroy") %>
						<%= link_to admin_role_path(role), data: { confirm: "Are you sure ?" }, method: :delete do %><i class="fa fa-trash"></i><% end %>
					<% end %>
			<% end %>
			</td>
	<% end %>
</tr>

app/views/admin/roles/_role_permission_collapse.html.erb
<style>
.card {
  position: relative;
  display: block;
  margin-bottom: 0.75rem;
  background-color: #fff;
  border-radius: 0.25rem;
  border: 1px solid rgba(0, 0, 0, 0.125)
}
.card-header:first-child {
  border-radius: calc(0.25rem - 1px) calc(0.25rem - 1px) 0 0;
  }
.card-header {
  padding: 0.50rem 1.25rem;
  margin-bottom: 0;
  background-color: #f5f5f5;
  border-bottom: 1px solid rgba(0, 0, 0, 0.125);
}
.mb-0 {
  margin-bottom: 0 !important;
}
h5, .h5 {
    font-size: 1.10rem;
}
a, a:link, a:visited {
  color: #38678b;
  text-decoration: underline;
}
.collapse {
  display: none;
}
.card-block {
    padding: 1.25rem;
}
table tr td {
  width: 10%;
}
</style>
<div id="accordion" role="tablist" aria-multiselectable="true">
  <% uniq_controller.each do |permission| %>
    <div class="card">
      <div class="card-header" role="tab" id="headingOne">
        <h5 class="mb-0">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <%= permission %>
          </a>
        </h5>
      </div>

      <% all_controller.each do |cont| %>
        <% if cont.subject_class == permission %>
          <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
            <div class="card-block">
              <table>
                <tr><td><%= I18n.locale == :en ? cont.name_en : cont.name_fr%></td>
                <td>
                <%= f.check_box :permission_ids, {multiple: true}, cont.id, nil %></td></tr>
              </table>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
<script>
$(document).ready(function() {
   $('.collapse').hide();
      // console.log($(this).find('div'))
    $('#headingOne').click(function() {
      if(!$('#collapseOne').is(':visible')) {
          $('.collapse').hide(400);
      }
      $('.collapse').toggle(400);
    });
// $('#headingOne').on('click',function(){
//   console.log("hiii");
//   console.log($(this).find('#headingOne').siblings('.collapse'))
//   // $(this).find('#headingOne').children('.collapse').show();
//     $('.collapse').show();
//   // $('.collapse').css("display","none");
// });
  //   if ($('.collapse').show()){
  //     $('#headingOne').on('click',function(){
  //       $('.collapse').hide();
  //     });
  //     console.log("hello")
  // }
});
</script>

app/views/admin/roles/edit.html.erb
<%= render "form" %>

app/views/admin/roles/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9 col-sm-9">
      <h2><%= t('activerecord.models.role.heading.main') %></h2>
    </div>
    <div class="col-md-3 col-sm-3">
    	<%= render "actions" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%# if has_permission(controller_path,"search") %>
        <!-- <form method="#" action="#" class="form-horizontal">
          <div id="search-information" class="box white-bg">
            <div class="form-heading">
                <h3>search</h3>
                <div class="divider dark-gray-bg"></div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-md-4 col-sm-4">
                  <label for="provider" class="col-sm-12">Provider</label>
                  <select name="provider" class="form-control ">
                    <option value=" ">Select a Provider</option>
                    <option value="1 ">1</option>
                    <option value="2 ">2</option>
                  </select>
                </div>
                <div class="col-md-4 col-sm-4">
                  <label for="model" class="col-sm-12">Model</label>
                  <select name="model" class="form-control ">
                    <option value=" ">Select a Model</option>
                    <option value="1 ">1</option>
                    <option value="2 ">2</option>
                  </select>
                </div>
                <div class="col-md-4 col-sm-4">
                  <label for="serial-number" class="col-sm-12">Serial number</label>
                  <select name="serial-number" class="form-control ">
                    <option value=" ">Select a Serial number</option>
                    <option value="1 ">1</option>
                    <option value="2 ">2</option>
                  </select>
                </div>
                <div class="col-md-2 col-md-offset-10 col-sm-2 col-sm-offset-10">
                  <button type="button " class="btn btn-default gray-bg pull-right">
                      Search
                  </button>
                </div>
              </div>
            </div>
          </div>
        </form> -->
      <%# end %>
      <div id="search-information" class="box white-bg">
        <div class="table-responsive">
          <table class="table">
            <thead class="table-heading">
              <tr>
                <th><%= t('activerecord.models.role.fields.Name In English') %></th>
                <th><%= t('activerecord.models.role.fields.Name In French') %></th>
                <% if has_permission(controller_path,"update") || has_permission(controller_path,"destroy") %>
                  <th><%= t('activerecord.models.role.fields.Action') %></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
            	<%= render @resources %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/roles/new.html.erb
<%= render "form" %>

app/views/admin/roles/show.html.erb
<br>
<%= render @resource %>
<%= link_to "All", admin_roles_path %>