config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  resources :payments
  concern :searchable do
    collection do
      get 'search'
    end
  end
  namespace :admin do
    resources :bank_accounts
    resources :companies
    resources :equipment
    resources :equipment_brands
    resources :equipment_models,concerns: [:searchable]
    resources :equipment_types
    resources :establishment_services
    resources :establishments
    resources :invoices_patients,concerns: [:searchable]
    resources :plans
    resources :positions
    resources :permissions
    resources :roles
    resources :skills
    resources :user_skills, only: [:show,:destroy]
    resources :specialities
    resources :forms
    resources :insurance_files, only: [:show,:destroy]
    resources :patients
    resources :patient_draft_data do
      collection do
        post 'save_upload_file', to: 'patient_draft_data/save_upload_file'
      end
    end
    resources :settings do
      collection do
        put 'update_settings',to: 'settings/update_settings'
      end
    end
    resources :users,concerns: [:searchable] do
      collection do
        get "pre_creation_user", to: 'users#pre_creation_user', :as => "pre_creation_user"
        get "accounts_to_active", to: 'users#accounts_to_active', :as => "accounts_to_active"
        get "pending_accounts", to: 'users#pending_accounts', :as => "pending_accounts"
        get "active_accounts", to: 'users#active_accounts', :as => "active_accounts"
        get "deactive_accounts", to: 'users#deactive_accounts', :as => "deactive_accounts"
        get "get_del_cust_by_country", to: 'users#get_del_cust_by_country', :as => "get_del_cust_by_country"
        get "set_current_role", to: 'users#set_current_role', :as => "set_current_role"
      end
      member do
        get "show_signature", to: 'users#show_signature', :as => "show_signature"
        put "delete_signature", to: 'users#delete_signature', :as => "delete_signature"
        get "active_account_form", to: 'users#active_account_form', :as => "active_account_form"
        post "update_account_status", to: 'users#update_account_status'
      end
    end
    # resources :users
    post "users/checkpostalcode", to: 'users#checkpostalcode', :as => "checkpostalcode"
    get "users/approved_data",to: 'users#approved_data', :as =>"approved_data"
    # get "users/pre_creation_user", to: 'users#pre_creation_user', :as => "pre_creation_user"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    password_expired: 'users/password_expired'

  }
  devise_scope :user do
    get 'signup' => 'users/registrations#new', :as => :sign_up
    # post 'signup' => 'users/registrations#new', :as => :sign_up
    authenticated :user do
      root 'dashboard#show'
    end
    get 'users/password_expired/change_password'
    post 'users/password_expired/update_password'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "devise/sessions#new"
  # root 'home#index'
  # resources "users"
  post '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  post '/set_role', to: 'settings#set_role_before_sign_up', as: :set_role_before_sign_up
  get '/get_users', to: 'settings#get_users'
  get '/find_customer_id', to: 'settings#find_customer_id'
  get '/find_patient_id', to: 'settings#find_patient_id'
  get '/find_provider_id', to: 'settings#find_provider_id'
  get '/find_delegate_customer_id', to: 'settings#find_delegate_customer_id'
  get '/find_salesman_before_sale_id', to: 'settings#find_salesman_before_sale_id'
  get '/find_salesman_sav_id', to: 'settings#find_salesman_sav_id'
  get '/find_physician_id', to: 'settings#find_physician_id'
  get '/get_all_skills', to: 'settings#get_all_skills'
  get '/mark_notification_as_read', to: 'settings#mark_notification_as_read'
  resources :forms do
    member do 
      get ':form_name' => "forms#payment_of_analysis", as: :payment_of_analysis
    end
  end

  resources :establishments, only: [:index]
  resources :establishment_services, only: [:index]
  resources :role_selection,only: [:index]
  post 'role_selection/get_role_id'
  get '/admin/establishment_form_check_postal_code', to: 'settings#establishment_form_check_postal_code'
  get '/admin/new_user_form_check_postal_code', to: 'settings#new_user_form_check_postal_code'
  get '/admin/change_notification_value', to: 'settings#change_notification_value'
end

app/models/establishment.rb
class Establishment < ApplicationRecord
	validates :bic,:iban,:name, :presence => true
	has_many :establishment_services, dependent: :destroy
	has_many :subscriptions , as: :entity,dependent: :destroy
	has_many :users,dependent: :destroy
	belongs_to :plan
end

app/controllers/admin/establishments_controller.rb
class Admin::EstablishmentsController < Admin::BaseController
	include Authorizations
 #  load_and_authorize_resource
	# before_filter :load_permissions

  def create
    super do |resource|
    	resource.subscriptions.build(subscription_date: Time.now,plan_id: resource.plan_id).save
    end
  end

  def update
    super do |resource|
    	r = resource.subscriptions.where(entity_id: resource.id)
      if r.present?
    	  r.update_all(plan_id: resource.plan_id)
      else
        resource.subscriptions.build(subscription_date: Time.now,plan_id: resource.plan_id).save
      end
    end
  end

  private

  def permitted_attributes
    ["salesman_id", "name", "iban", "bic", "address", "postal_code", "city", "country","plan_id"]
  end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
	# inherit_resources
	def index
		@establishments = Establishment.all
		render json: @establishments
	end
end

app/helpers/admin/establishments_helper.rb
module Admin::EstablishmentsHelper
end

app/views/admin/establishments/_actions.html.erb
<%= link_to t('establishment.new_establishment'), new_admin_establishment_path,class: "btn btn-default gray-bg",style: "margin-top: 10px;" %>

app/views/admin/establishments/_establishment.html.erb
<tr>
	<td><%= establishment.name %></td>
	<td><%= establishment.iban %></td>
	<td><%= establishment.bic %></td>
	<% if has_permission(controller_path,"update") || has_permission(controller_path,"destroy") %>
		<td>
			<% if has_permission(controller_path,"update") %>
				<%= link_to edit_admin_establishment_path(establishment) do %><i class="fa fa-edit"></i><% end %>
			<% end %>
			<% if has_permission(controller_path,"destroy") %>
				<%= link_to admin_establishment_path(establishment), data: { confirm: "Are you sure ?" }, method: :delete do %><i class="fa fa-trash"></i><% end %>
			<% end %>
		</td>
	<% end %>
</tr>

app/views/admin/establishments/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <h2><%= action_type(@resource) %> Establishment</h2>
    </div>
  </div>
  <div class="row">
  	<div class="has-error">
  	  <% if @resource.errors.any? %>
  	    <div class="blockquote-box clearfix">
  	      <span class="help-block">
  	       <b>ERROR:</b>
  	        <ul>
  		        <% @resource.errors.full_messages.each do |msg| %>
  		          <li><%= msg %></li>
  		      	<% end %>
  	     		</ul>
  	     </span>
  	    </div>
  	  <% end %>
  	</div>
  </div>
  <div class="row">
    <div class="col-md-12">
    	<%= form_for [:admin, @resource],class: "form-horizontal" do |f| %>
        <div id="search-information" class="box white-bg">
          <div class="form-group">
            <div class="row">
              <div class="col-md-6 col-sm-6">
                <label for="user" class="col-sm-12"><%= t('activerecord.models.establishment.fields.Salesman') %></label>
                <% @roles = Role.where("name_en LIKE ?", "Salesman%") %>
                <% salesman_role = current_user.has_role?("salesman") || current_user.has_role?("salesman_before_sale") %>
                <% if params[:action] == "new" %>
                  <%= f.select(:user_ids, User.joins(:user_roles).where("role_id IN (?) ", @roles.ids ).uniq.order("first_name").collect {|c| [c.first_name + " " + c.last_name , c.id ]},{:selected => (salesman_role && params[:action] == "new" ? current_user.id : '')},{class: "form-control", name: "establishment[salesman_id]"}) %>
                <% elsif params[:action] == "edit" %>
                  <%= f.select(:user_ids, User.joins(:user_roles).where("role_id IN (?) ", @roles.ids ).uniq.order("first_name").collect {|c| [c.first_name + " " + c.last_name , c.id ]},{:selected => @resource.salesman_id},{class: "form-control", name: "establishment[salesman_id]"}) %>
                <% end %>
              </div>
              <div class="col-md-6 col-sm-6">
                <label for="Name" class="col-sm-12"><%= t('activerecord.models.establishment.fields.Name') %></label>
               	<%= f.text_field :name,class: "form-control",placeholder: "Name",required: "required" %>
              </div>
              <div class="col-md-6 col-sm-6">
                <label for="iban" class="col-sm-12"><%= t('activerecord.models.establishment.fields.IBAN') %></label>
               	<%= f.text_field :iban,class: "form-control",placeholder: "iban",required: "required" %>
              </div>
              <div class="col-md-6 col-sm-6">
                <label for="bic" class="col-sm-12"><%= t('activerecord.models.establishment.fields.BIC') %></label>
               	<%= f.text_field :bic,class: "form-control",placeholder: "bic",required: "required" %>
              </div>
               <div class="col-md-6 col-sm-6">
                <label for="plan" class="col-sm-12"><%= t('activerecord.models.establishment.fields.Plan') %></label>
                <%= f.select(:plan_id, Plan.all.collect {|c| [c.name, c.id ]},{},{class: "form-control "}) %>
              </div>
              <div class="col-md-6 col-sm-6">
                <label for="address" class="col-sm-12"><%= t('activerecord.models.establishment.fields.address') %></label>
                <%= f.text_field :address,class: "form-control",placeholder: "address" %>
              </div>
              <div class="col-md-6 col-sm-6">
                <label for="postal_code" class="col-sm-12"><%= t('activerecord.models.establishment.fields.Postal Code') %></label>
                <%= f.text_field :postal_code,class: "form-control",placeholder: "postal code" %>
              </div>
              <div class="col-md-6 col-sm-6">
                <label for="city" class="col-sm-12"><%= t('activerecord.models.establishment.fields.City') %></label>
                <%= f.text_field :city,class: "form-control",placeholder: "city" %>
              </div>
              <div class="col-md-6 col-sm-6 country-select">
                <label for="country" class="col-sm-12"><%= t('activerecord.models.establishment.fields.Country') %></label>
                <%= f.select(:country, Country.all.collect {|c| [c.name_with_tel_code, c.telephone_code ]},{},{class: "form-control country"}) %>
              </div>
              <div class="col-md-2 col-md-offset-10 col-sm-4">
              	<!-- <%= f.submit "Add",class: "btn btn-default gray-bg pull-right" %> -->
                <button type="button" onclick="check_postal_code_submit_form('<%= action_name %>')" class="btn btn-default gray-bg pull-right"><%= action_type_for_button(@resource) %></button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/establishments/edit.html.erb
<%= render "form" %>

app/views/admin/establishments/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9 col-sm-9">
      <h2><%= t('activerecord.models.establishment.heading.main') %></h2>
    </div>
    <div class="col-md-3 col-sm-3">
      <% if has_permission(controller_path,"create") %>
    	 <%= render "actions" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%# if has_permission(controller_path,"search") %>
        <!-- <form method="#" action="#" class="form-horizontal">
          <div id="search-information" class="box white-bg">
            <div class="form-heading">
                <h3>search</h3>
                <div class="divider dark-gray-bg"></div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-md-4 col-sm-4">
                  <label for="provider" class="col-sm-12">Provider</label>
                  <select name="provider" class="form-control ">
                    <option value=" ">Select a Provider</option>
                    <option value="1 ">1</option>
                    <option value="2 ">2</option>
                  </select>
                </div>
                <div class="col-md-4 col-sm-4">
                  <label for="model" class="col-sm-12">Model</label>
                  <select name="model" class="form-control ">
                    <option value=" ">Select a Model</option>
                    <option value="1 ">1</option>
                    <option value="2 ">2</option>
                  </select>
                </div>
                <div class="col-md-4 col-sm-4">
                  <label for="serial-number" class="col-sm-12">Serial number</label>
                  <select name="serial-number" class="form-control ">
                    <option value=" ">Select a Serial number</option>
                    <option value="1 ">1</option>
                    <option value="2 ">2</option>
                  </select>
                </div>
                <div class="col-md-2 col-md-offset-10 col-sm-2 col-sm-offset-10">
                  <button type="button " class="btn btn-default gray-bg pull-right">
                      Search
                  </button>
                </div>
              </div>
            </div>
          </div>
        </form> -->
      <%# end %>
      <div id="search-information" class="box white-bg">
        <div class="table-responsive">
          <table class="table">
            <thead class="table-heading">
              <tr>
                <th><%= t('activerecord.models.establishment.fields.Name') %></th>
                <th><%= t('activerecord.models.establishment.fields.IBAN') %></th>
								<th><%= t('activerecord.models.establishment.fields.BIC') %></th>
                <% if has_permission(controller_path,"update") || has_permission(controller_path,"destroy") %>
                  <th><%= t('activerecord.models.establishment.fields.Action') %></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
            	<%= render @resources %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/establishments/new.html.erb
<%= render "form" %>

app/views/admin/establishments/show.html.erb
<br>
<%= render @resource %>
<%= link_to "All", admin_establishments_path %>